### ISSUE TITLE
Restructure the repo with @richardfuchs and @JoHeinrich

### ISSUE THREAD

**Issue by elisabethhoppe** [JoHeinrich/amos-ss16-proj5#16]
In a new branch: restructure the repo, create new subdirectories according to the architecture plan.
Merge the restructuring branch back to the main branch.

**Comment by richardfuchs** [comment]
Done
See e898530c58a5e34318126a6dfeca23930664aad0 6f3614766936e9c333ab47eb368544011e49b5fd 7d8d01242ec333d5e98f2719a6894eca365f9410 42d43723bff2cd5287e16df17b3e7a6275b718ab 74735728d266e8fb2e5b04a8ff082d0b3be27c97 90042b867943f303f1bafc9a7b1f7157bda078d4
